# Generated by Django 4.2.28 on 2026-03-03 13:47

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mudar_senha', models.BooleanField(default=False, verbose_name='Forçar Troca de Senha')),
                ('email_verificado', models.BooleanField(default=False, verbose_name='Email Verificado')),
                ('tipo_profissional', models.CharField(blank=True, choices=[('MED', 'Médico'), ('ENF', 'Enfermeiro'), ('NUT', 'Nutricionista'), ('FAR', 'Farmacêutico')], max_length=3, null=True, verbose_name='Tipo Profissional')),
                ('tipo_registro', models.CharField(blank=True, choices=[('CRM', 'CRM'), ('COREN', 'COREN'), ('CRN', 'CRN'), ('CRF', 'CRF')], max_length=10, null=True, verbose_name='Conselho (Ex: CRM)')),
                ('registro_profissional', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Conselho')),
                ('drt', models.CharField(blank=True, max_length=20, null=True, verbose_name='DRT / Matrícula')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('score_prevent_valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score Prevent (%)')),
                ('subjetivo', models.TextField(verbose_name='S - Subjetivo')),
                ('objetivo', models.TextField(verbose_name='O - Objetivo')),
                ('avaliacao', models.TextField(verbose_name='A - Avaliação')),
                ('plano', models.TextField(verbose_name='P - Plano')),
                ('cid10_1', models.CharField(max_length=10, verbose_name='CID-10 Principal')),
                ('cid10_2', models.CharField(blank=True, max_length=10, null=True)),
                ('cid10_3', models.CharField(blank=True, max_length=10, null=True)),
                ('cid11_correspondente', models.CharField(blank=True, max_length=200)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('etnia', models.CharField(choices=[('Branca', 'Branca'), ('Parda', 'Parda'), ('Negra', 'Negra'), ('Indígena', 'Indígena')], max_length=20)),
                ('data_nascimento', models.DateField()),
                ('data_insercao', models.DateField(default=datetime.date.today)),
                ('data_alta', models.DateField(blank=True, null=True)),
                ('municipio', models.CharField(default='Caraguatatuba', max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('siresp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número CROSS / SIRESP')),
                ('altura_ultima', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriagemHipertensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_triagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('pa_sistolica_1', models.IntegerField(verbose_name='PAS 1')),
                ('pa_diastolica_1', models.IntegerField(verbose_name='PAD 1')),
                ('pa_sistolica_2', models.IntegerField(verbose_name='PAS 2')),
                ('pa_diastolica_2', models.IntegerField(verbose_name='PAD 2')),
                ('pa_sistolica_3', models.IntegerField(verbose_name='PAS 3')),
                ('pa_diastolica_3', models.IntegerField(verbose_name='PAD 3')),
                ('media_sistolica', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('media_diastolica', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('qtd_antihipertensivos', models.IntegerField(default=0)),
                ('risco_loa_presente', models.BooleanField(default=False)),
                ('status_elegibilidade', models.CharField(choices=[('ELEGIVEL', 'Elegível'), ('CONTRARREFERENCIA', 'Não Elegível')], max_length=20)),
                ('motivo_desfecho', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triagens_has', to='core.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescricaoMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prescricao', models.DateTimeField(auto_now_add=True)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescricao', to='core.atendimentomedico')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100)),
                ('principio_ativo', models.CharField(max_length=100)),
                ('dose_padrao', models.CharField(max_length=50)),
                ('nomes_comerciais', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('is_remume', models.BooleanField(default=False, verbose_name='Pertence ao SUS/REMUME')),
            ],
            options={
                'ordering': ['classe', 'principio_ativo'],
                'unique_together': {('principio_ativo', 'dose_padrao')},
            },
        ),
        migrations.CreateModel(
            name='ItemPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_nome', models.CharField(max_length=200)),
                ('concentracao', models.CharField(max_length=100)),
                ('posologia', models.TextField()),
                ('quantidade', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('CONTINUO', 'Uso Contínuo'), ('TEMPORARIO', 'Uso Temporário'), ('CONTROLADO', 'Controle Especial')], default='CONTINUO', max_length=20)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.prescricaomedica')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoPrevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('colesterol_total', models.IntegerField(verbose_name='Colesterol Total (mg/dL)')),
                ('hdl', models.IntegerField(verbose_name='HDL (mg/dL)')),
                ('pressao_sistolica', models.IntegerField(verbose_name='PAS (mmHg)')),
                ('em_tratamento_has', models.BooleanField(default=True, verbose_name='Em tto Anti-hipertensivo?')),
                ('tem_diabetes', models.BooleanField(default=False)),
                ('fumante', models.BooleanField(default=False)),
                ('tfg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='eGFR (ml/min)')),
                ('risco_10_anos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Risco 10 Anos (%)')),
                ('risco_30_anos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Risco 30 Anos (%)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
            options={
                'verbose_name': 'Avaliação PREVENT',
            },
        ),
        migrations.CreateModel(
            name='AtendimentoMultidisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura (m)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='IMC')),
                ('circunferencia_abdominal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Circunferência Abdominal (cm)')),
                ('tem_diabetes', models.BooleanField(default=False)),
                ('tipo_diabetes', models.CharField(blank=True, choices=[('1', 'Tipo 1'), ('2', 'Tipo 2'), ('G', 'Gestacional')], max_length=1, null=True)),
                ('fumante', models.BooleanField(default=False)),
                ('macos_por_dia', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('anos_fumando', models.IntegerField(blank=True, null=True)),
                ('carga_tabagica', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Anos-Maço')),
                ('tem_lesao_orgao', models.BooleanField(default=False)),
                ('loa_coracao', models.BooleanField(default=False, verbose_name='Coração (HVE/IAM)')),
                ('loa_cerebro', models.BooleanField(default=False, verbose_name='Cérebro (AVC/AIT)')),
                ('loa_rins', models.BooleanField(default=False, verbose_name='Rins (Doença Renal)')),
                ('loa_arterias', models.BooleanField(default=False, verbose_name='Artérias Periféricas')),
                ('loa_olhos', models.BooleanField(default=False, verbose_name='Retinopatia')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_multi', to='core.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atendimentomedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.CreateModel(
            name='Afericao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_afericao', models.DateTimeField(auto_now_add=True)),
                ('pressao_sistolica', models.IntegerField()),
                ('pressao_diastolica', models.IntegerField()),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('medicamentos', models.ManyToManyField(blank=True, to='core.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afericoes', to='core.paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_afericao'],
            },
        ),
    ]
