# Generated by Django 4.2.28 on 2026-03-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='fonte_renda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='queixa_principal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='rede_familiar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='religiao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='renda_familiar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='reside_com',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
