# Generated by Django 6.0 on 2026-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_alta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
