# Generated by Django 6.0 on 2026-01-09 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_data_alta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoMultidisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura (m)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='IMC')),
                ('circunferencia_abdominal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Circunferência Abdominal (cm)')),
                ('tem_diabetes', models.BooleanField(default=False, verbose_name='Possui Diabetes?')),
                ('tem_lesao_orgao', models.BooleanField(default=False, verbose_name='Possui Lesão de Órgão-Alvo?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações / Conduta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_multi', to='core.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
