# Generated by Django 6.0 on 2026-01-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atendimentomultidisciplinar'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='anos_fumando',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='carga_tabagica',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Anos-Maço'),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='fumante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='loa_arterias',
            field=models.BooleanField(default=False, verbose_name='Artérias Periféricas'),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='loa_cerebro',
            field=models.BooleanField(default=False, verbose_name='Cérebro (AVC/AIT)'),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='loa_coracao',
            field=models.BooleanField(default=False, verbose_name='Coração (HVE/IAM)'),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='loa_olhos',
            field=models.BooleanField(default=False, verbose_name='Retinopatia'),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='loa_rins',
            field=models.BooleanField(default=False, verbose_name='Rins (Doença Renal)'),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='macos_por_dia',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomultidisciplinar',
            name='tipo_diabetes',
            field=models.CharField(blank=True, choices=[('1', 'Tipo 1'), ('2', 'Tipo 2'), ('G', 'Gestacional')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='atendimentomultidisciplinar',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimentomultidisciplinar',
            name='tem_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atendimentomultidisciplinar',
            name='tem_lesao_orgao',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AvaliacaoPrevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('colesterol_total', models.IntegerField(verbose_name='Colesterol Total (mg/dL)')),
                ('hdl', models.IntegerField(verbose_name='HDL (mg/dL)')),
                ('pressao_sistolica', models.IntegerField(verbose_name='PAS (mmHg)')),
                ('em_tratamento_has', models.BooleanField(default=True, verbose_name='Em tto Anti-hipertensivo?')),
                ('tem_diabetes', models.BooleanField(default=False)),
                ('fumante', models.BooleanField(default=False)),
                ('tfg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='eGFR (ml/min)')),
                ('risco_10_anos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Risco 10 Anos (%)')),
                ('risco_30_anos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Risco 30 Anos (%)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
            options={
                'verbose_name': 'Avaliação PREVENT',
            },
        ),
    ]
