# Generated by Django 6.0 on 2026-01-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atendimentomultidisciplinar_anos_fumando_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_verificado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mudar_senha',
        ),
        migrations.AddField(
            model_name='usuario',
            name='registro_profissional',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº do Conselho'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_profissional',
            field=models.CharField(blank=True, choices=[('MED', 'Médico'), ('ENF', 'Enfermeiro'), ('NUT', 'Nutricionista'), ('FAR', 'Farmacêutico')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_registro',
            field=models.CharField(blank=True, choices=[('CRM', 'CRM'), ('COREN', 'COREN'), ('CRN', 'CRN'), ('CRF', 'CRF')], max_length=10, null=True, verbose_name='Conselho (Ex: CRM)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='drt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DRT / Matrícula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
