# Generated by Django 6.0 on 2026-01-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usuario_email_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Email Verificado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mudar_senha',
            field=models.BooleanField(default=False, verbose_name='Forçar Troca de Senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='registro_profissional',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Conselho'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_profissional',
            field=models.CharField(blank=True, choices=[('MED', 'Médico'), ('ENF', 'Enfermeiro'), ('NUT', 'Nutricionista'), ('FAR', 'Farmacêutico')], max_length=3, null=True, verbose_name='Tipo Profissional'),
        ),
    ]
