# Generated by Django 6.0 on 2026-01-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_email_verificado_usuario_mudar_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='siresp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número CROSS / SIRESP'),
        ),
    ]
