# Generated by Django 6.0 on 2026-01-14 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paciente_siresp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('score_prevent_valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score Prevent (%)')),
                ('subjetivo', models.TextField(verbose_name='S - Subjetivo')),
                ('objetivo', models.TextField(verbose_name='O - Objetivo')),
                ('avaliacao', models.TextField(verbose_name='A - Avaliação')),
                ('plano', models.TextField(verbose_name='P - Plano')),
                ('cid10_1', models.CharField(max_length=10, verbose_name='CID-10 Principal')),
                ('cid10_2', models.CharField(blank=True, max_length=10, null=True)),
                ('cid10_3', models.CharField(blank=True, max_length=10, null=True)),
                ('cid11_correspondente', models.CharField(blank=True, max_length=200)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PrescricaoMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prescricao', models.DateTimeField(auto_now_add=True)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescricao', to='core.atendimentomedico')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_nome', models.CharField(max_length=200)),
                ('concentracao', models.CharField(max_length=100)),
                ('posologia', models.TextField()),
                ('quantidade', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('CONTINUO', 'Uso Contínuo'), ('TEMPORARIO', 'Uso Temporário'), ('CONTROLADO', 'Controle Especial')], default='CONTINUO', max_length=20)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.prescricaomedica')),
            ],
        ),
        migrations.CreateModel(
            name='TriagemHipertensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_triagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('pa_sistolica_1', models.IntegerField(verbose_name='PAS 1')),
                ('pa_diastolica_1', models.IntegerField(verbose_name='PAD 1')),
                ('pa_sistolica_2', models.IntegerField(verbose_name='PAS 2')),
                ('pa_diastolica_2', models.IntegerField(verbose_name='PAD 2')),
                ('pa_sistolica_3', models.IntegerField(verbose_name='PAS 3')),
                ('pa_diastolica_3', models.IntegerField(verbose_name='PAD 3')),
                ('media_sistolica', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('media_diastolica', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('qtd_antihipertensivos', models.IntegerField(default=0)),
                ('risco_loa_presente', models.BooleanField(default=False)),
                ('status_elegibilidade', models.CharField(choices=[('ELEGIVEL', 'Elegível'), ('CONTRARREFERENCIA', 'Não Elegível')], max_length=20)),
                ('motivo_desfecho', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triagens_has', to='core.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
