# Generated by Django 6.0 on 2026-01-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_atendimentomedico_prescricaomedica_itemprescricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='principio_ativo',
            field=models.CharField(max_length=100),
        ),
    ]
