# Generated by Django 6.0 on 2026-01-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_medicamento_principio_ativo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicamento',
            unique_together={('principio_ativo', 'dose_padrao')},
        ),
    ]
