# Generated by Django 6.0 on 2026-01-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_medicamento_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='is_remume',
            field=models.BooleanField(default=False, verbose_name='Pertence ao SUS/REMUME'),
        ),
    ]
